- name: swagger-petstore-v2.1.0.json
  url: >-
    https://api.github.com/repositories/158004752/contents/tests/fixtures/collection/swagger-petstore-v2.1.0.json?ref=5683456a1420af15fc61333a3557a5ca29738899
  owner: mandrean
  repo: postman-collection-rs
  domain_process: 0
  html_process: 0
- name: file-param.input.json
  url: >-
    https://api.github.com/repositories/73833932/contents/tests/fixtures/transformation/parameters/file-param.input.json?ref=d537c895375e7ce5b8cc85c8f91a2c1030512253
  owner: Apicurio
  repo: oai-ts-core
  domain_process: 0
  html_process: 0
- name: package.json
  url: >-
    https://api.github.com/repositories/89764922/contents/package.json?ref=4d2fc5b9a5c5c54774efaf0f7dd1138b2c6114aa
  owner: bharatpatil21
  repo: image-upload-nodejs-express
  domain_process: 0
  html_process: 0
- name: package.json
  url: >-
    https://api.github.com/repositories/193774214/contents/package.json?ref=f7726ec843aa60ec6af49b80f0837814e296f16c
  owner: seansund
  repo: my-new-project
  domain_process: 0
  html_process: 0
- name: manifest.json
  url: >-
    https://api.github.com/repositories/66757464/contents/public/manifest.json?ref=d98396b7b7255e088f3f526ed0a34f13e2f5119d
  owner: essuraj
  repo: swagger-toolbox
  domain_process: 0
  html_process: 0
- name: manifest.json
  url: >-
    https://api.github.com/repositories/89005663/contents/workshops/swag-my-finch-up/manifest.json?ref=e259cfd089632c1e623e9142c618f4b15b5916ef
  owner: lunatech-labs
  repo: lunatech-competence-center-online
  domain_process: 0
  html_process: 0
- name: spec.json
  url: >-
    https://api.github.com/repositories/185369406/contents/lib/spec.json?ref=4effe92c3c2af796111dbf2b04166bbde551e9f0
  owner: flowground
  repo: hackathonwatch-com-connector
  domain_process: 0
  html_process: 0
- name: spark-md5.json
  url: >-
    https://api.github.com/repositories/73249815/contents/dependents/spark-md5.json?ref=d8f40fe4968d49a2e2c25e9ac3ef7389be95e14f
  owner: nice-registry
  repo: dependent-packages
  domain_process: 0
  html_process: 0
- name: Dockerrun.aws.json
  url: >-
    https://api.github.com/repositories/54547007/contents/Dockerrun.aws.json?ref=00f78a3ceff4d3e71ff9cf00fdf9020f27c2e7f6
  owner: muthusk
  repo: swaggerelasticbeanstalk
  domain_process: 0
  html_process: 0
- name: package.json
  url: >-
    https://api.github.com/repositories/193249752/contents/package.json?ref=e3bd8f31bffb02dc5d0679f3d0aeb3dc3054383d
  owner: mjperrins
  repo: products-bff
  domain_process: 0
  html_process: 0
- name: esformatter-semicolons.json
  url: >-
    https://api.github.com/repositories/73249815/contents/devDependents/esformatter-semicolons.json?ref=d8f40fe4968d49a2e2c25e9ac3ef7389be95e14f
  owner: nice-registry
  repo: dependent-packages
  domain_process: 0
  html_process: 0
- name: swagger-petstore-v2.0.0.json
  url: >-
    https://api.github.com/repositories/158004752/contents/tests/fixtures/collection/swagger-petstore-v2.0.0.json?ref=5683456a1420af15fc61333a3557a5ca29738899
  owner: mandrean
  repo: postman-collection-rs
  domain_process: 0
  html_process: 0
- name: package.json
  url: >-
    https://api.github.com/repositories/89094385/contents/package.json?ref=07c8b38b5eee6767e8e484033357199333c22784
  owner: rai-project
  repo: mlmodelscope
  domain_process: 0
  html_process: 0
- name: ecs_swagger_prod_taskdefinition.json
  url: >-
    https://api.github.com/repositories/158750314/contents/ecs/ecs_swagger_prod_taskdefinition.json?ref=6b3a6fe2b66e7a257a7eee1ece9c2dbb44f3d317
  owner: jasonwlcx
  repo: flask_notebook
  domain_process: 0
  html_process: 0
- name: rest-soap-transformation.json
  url: >-
    https://api.github.com/repositories/107580014/contents/support/templates/rest-soap-transformation.json?ref=85ab825686048f8f564a917b94f210707cbed877
  owner: masales
  repo: proxySoapRest
  domain_process: 0
  html_process: 0
- name: coach-bags-new-arrival.json
  url: >-
    https://api.github.com/repositories/50018668/contents/experiment/coach-bags-new-arrival.json?ref=92a2eadf6abeeeb4a2e9a49a329e8b731b27c34d
  owner: niczy
  repo: buyyub
  domain_process: 0
  html_process: 0
- name: community-contributed.json
  url: >-
    https://api.github.com/repositories/148679594/contents/app-web/registry/community-contributed.json?ref=d7a0f0bfceb0784678777f5e48830d3f36e48e5c
  owner: bcgov
  repo: devhub-app-web
  domain_process: 0
  html_process: 0
- name: file-param.expected.json
  url: >-
    https://api.github.com/repositories/73833932/contents/tests/fixtures/transformation/parameters/file-param.expected.json?ref=d537c895375e7ce5b8cc85c8f91a2c1030512253
  owner: Apicurio
  repo: oai-ts-core
  domain_process: 0
  html_process: 0
- name: ecs_swagger_prod_taskdefinition.json
  url: >-
    https://api.github.com/repositories/182406192/contents/ecs/ecs_swagger_prod_taskdefinition.json?ref=94e0b58488be6165e09c2c829e7c4f5c6a37aa8b
  owner: serpent-tracker
  repo: serpent-tracker
  domain_process: 0
  html_process: 0
- name: ecs_swagger_stage_taskdefinition.json
  url: >-
    https://api.github.com/repositories/182406192/contents/ecs/ecs_swagger_stage_taskdefinition.json?ref=94e0b58488be6165e09c2c829e7c4f5c6a37aa8b
  owner: serpent-tracker
  repo: serpent-tracker
  domain_process: 0
  html_process: 0
- name: ecs_swagger_prod_taskdefinition.json
  url: >-
    https://api.github.com/repositories/117706955/contents/ecs/ecs_swagger_prod_taskdefinition.json?ref=26108f409eba7caa306bbb8e17df9de1624c6d90
  owner: nickvandewiele
  repo: testdriven-microservices
  domain_process: 0
  html_process: 0
- name: ecs_swagger_stage_taskdefinition.json
  url: >-
    https://api.github.com/repositories/117706955/contents/ecs/ecs_swagger_stage_taskdefinition.json?ref=26108f409eba7caa306bbb8e17df9de1624c6d90
  owner: nickvandewiele
  repo: testdriven-microservices
  domain_process: 0
  html_process: 0
- name: docker-swagger-codegen-langs.json
  url: >-
    https://api.github.com/repositories/91177819/contents/templates/docker-swagger-codegen-langs.json?ref=0f3a34dc843e4a61cc9a6e2989e38b32ec6afc78
  owner: cliffano
  repo: packer-swaggy-c
  domain_process: 0
  html_process: 0
- name: swagger.json
  url: >-
    https://api.github.com/repositories/111243547/contents/swagger-src/swagger.json?ref=123781a0d4e346fac8838322bd0c3b5df107e9cb
  owner: bartekzawadka
  repo: threesixty-service
  domain_process: 0
  html_process: 0
- name: swagger.json
  url: >-
    https://api.github.com/repositories/122467722/contents/Functions/FunctionCode/News/.azurefunctions/swagger/swagger.json?ref=e41207f8419a4d0670b2d796001a8ca55406f8a8
  owner: gpeturgit
  repo: AnnataBuisnessPlatformAppsDev
  domain_process: 0
  html_process: 0
- name: manifest.json
  url: >-
    https://api.github.com/repositories/87203439/contents/manifest.json?ref=b9858b668f5b01d90aecfa37fc2bfea459ff04b5
  owner: Svaigas
  repo: mad_img
  domain_process: 0
  html_process: 0
- name: swagger.json
  url: >-
    https://api.github.com/repositories/185366490/contents/swagger/swagger.json?ref=e86f6fe685c4cb6179eccbea69069817b252caa2
  owner: priyankad96
  repo: Fruits-node-api
  domain_process: 0
  html_process: 0
- name: package.json
  url: >-
    https://api.github.com/repositories/194170508/contents/package.json?ref=020b88fbe729db401f5726c38abb68ef19e59ce0
  owner: mjperrins
  repo: lazzero-bff01
  domain_process: 0
  html_process: 0
- name: openapi.json
  url: >-
    https://api.github.com/repositories/183158297/contents/example/doc/openapi.json?ref=98d1799dc55fbeba57af1255408b4350892f58cc
  owner: nangongxixi
  repo: api-engine
  domain_process: 0
  html_process: 0
- name: package.json
  url: >-
    https://api.github.com/repositories/117576366/contents/package.json?ref=ed2cebfa15765c1b02ae07a6844ff65a9afec147
  owner: aditya0562
  repo: test1
  domain_process: 0
  html_process: 0
- name: ecs_swagger_prod_taskdefinition.json
  url: >-
    https://api.github.com/repositories/183332649/contents/ecs/ecs_swagger_prod_taskdefinition.json?ref=b1fd226d30068a92fe04ed998ff790a87f3cb3e0
  owner: smeyerhot
  repo: testdriven
  domain_process: 0
  html_process: 0
- name: ecs_swagger_stage_taskdefinition.json
  url: >-
    https://api.github.com/repositories/183332649/contents/ecs/ecs_swagger_stage_taskdefinition.json?ref=b1fd226d30068a92fe04ed998ff790a87f3cb3e0
  owner: smeyerhot
  repo: testdriven
  domain_process: 0
  html_process: 0
- name: swagger.json
  url: >-
    https://api.github.com/repositories/135355068/contents/swagger/api/swagger/swagger.json?ref=f6c6ee9b8d223213869c85b8ebbdbf5f69791e10
  owner: giplash
  repo: configure
  domain_process: 0
  html_process: 0
- name: 1109444128331436032_batch_statuses.json
  url: >-
    https://api.github.com/repositories/181983722/contents/scandal/json_data1/college_cheating_scandal/1109444128331436032_batch_statuses.json?ref=cb4a7d0881900afa3dd1302deef35ce1790ee4a6
  owner: CarlyLarsson
  repo: CS273_Project
  domain_process: 0
  html_process: 0
- name: ecs_swagger_prod_taskdefinition.json
  url: >-
    https://api.github.com/repositories/148853362/contents/ecs/ecs_swagger_prod_taskdefinition.json?ref=c70863e5b067b61a6396a85585c926e77c047792
  owner: leapwing
  repo: testdriven-app
  domain_process: 0
  html_process: 0
- name: ecs_swagger_stage_taskdefinition.json
  url: >-
    https://api.github.com/repositories/148853362/contents/ecs/ecs_swagger_stage_taskdefinition.json?ref=c70863e5b067b61a6396a85585c926e77c047792
  owner: leapwing
  repo: testdriven-app
  domain_process: 0
  html_process: 0
- name: docker-compose.json
  url: >-
    https://api.github.com/repositories/148115945/contents/docker/bin/docker-compose.json?ref=2b09aee93f267d097934cf2bc77304d6ba8dd2cb
  owner: borankux
  repo: docker-multi-project-boilerplate
  domain_process: 0
  html_process: 0
- name: ecs_swagger_prod_taskdefinition.json
  url: >-
    https://api.github.com/repositories/141150643/contents/ecs/ecs_swagger_prod_taskdefinition.json?ref=2e250771bf70ed752d94b756243db308f22311c0
  owner: kjuulh
  repo: PythonMicroservices-v2
  domain_process: 0
  html_process: 0
- name: ecs_swagger_stage_taskdefinition.json
  url: >-
    https://api.github.com/repositories/141150643/contents/ecs/ecs_swagger_stage_taskdefinition.json?ref=2e250771bf70ed752d94b756243db308f22311c0
  owner: kjuulh
  repo: PythonMicroservices-v2
  domain_process: 0
  html_process: 0
