- name: bower.json
  url: >-
    https://github.com/hothson/sc_test/blob/898c24f3e01ecb6c8387efc56b64d83264fcb36f/node-sbadmin/bower.json
  owner: hothson
  repo: sc_test
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/keerthiD0589/jhipsterSampleApplication/blob/de4788402ae905870c400da791ecf522efdf3d5f/.yo-rc.json
  owner: keerthiD0589
  repo: jhipsterSampleApplication
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/zen1st/blogs/blob/f94a906f93c31c5de67cae2761fa6555eb487ba4/.yo-rc.json
  owner: zen1st
  repo: blogs
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/ButterflyApp/OnceAgainGames/blob/1e731b1e5f7b5c67f6c40dae66736d0e41c8f3c0/.yo-rc.json
  owner: ButterflyApp
  repo: OnceAgainGames
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/nelson54/lost-cities-java/blob/c24bdd7a244954338626dfd2880dd6597209124d/.yo-rc.json
  owner: nelson54
  repo: lost-cities-java
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/campino-rocks/b2b/blob/503413dda0dcafe3ca9c19fd39590e0af123dcde/.yo-rc.json
  owner: campino-rocks
  repo: b2b
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/onlyshishir/jhipsterSampleApplication/blob/508e504250ce48eb5814608bfc45529ef251a29a/.yo-rc.json
  owner: onlyshishir
  repo: jhipsterSampleApplication
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/firatgursoy/jhipsterSampleApplication/blob/cf58b1a69e5a95c10b3b3979f43cb5ab8e26ebe8/.yo-rc.json
  owner: firatgursoy
  repo: jhipsterSampleApplication
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/SecurityRAT/gateway/blob/b571261f0cbac3c08f8029175c62d9e8756e0356/.yo-rc.json
  owner: SecurityRAT
  repo: gateway
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/Djeukam/monapplication/blob/b5a97bc42000c949dab5305b3d2ba969483c0c88/.yo-rc.json
  owner: Djeukam
  repo: monapplication
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/vishalpatidar00789/suchaz-apis/blob/38ed8d19e25898c72c28bcb3d20cbde800733457/.yo-rc.json
  owner: vishalpatidar00789
  repo: suchaz-apis
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/typhoon51280/jhipsterApp/blob/4095e84d9ad0eb80cf55ce9d78bf7f50733f6fa9/.yo-rc.json
  owner: typhoon51280
  repo: jhipsterApp
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/feherpedro/dontwant2fail/blob/f91a72c935e48d404a47099c4e5e81d054d67e22/.yo-rc.json
  owner: feherpedro
  repo: dontwant2fail
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/spring7/mySweetShop/blob/3b49e44aa5001ee1096c60d50ccb41331d9fe2e3/.yo-rc.json
  owner: spring7
  repo: mySweetShop
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/juliensutter/babyfoot/blob/e8ffcbb635896cee28ba93936698f71bf51a6eac/.yo-rc.json
  owner: juliensutter
  repo: babyfoot
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/ronnyling/YamlPropertyMapper/blob/317deaaa019945a076ded4343cbb762d3bf8fbcf/.yo-rc.json
  owner: ronnyling
  repo: YamlPropertyMapper
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/srikant199/cricket/blob/79724ee55c0c2f56fb14f99b7973f40eb224748b/.yo-rc.json
  owner: srikant199
  repo: cricket
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/iccorp/shana/blob/38e108a738951657949f64eecfd4e285bc335dd5/.yo-rc.json
  owner: iccorp
  repo: shana
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/tuannt39-study/jhipster-v4/blob/94511d9ab8e0c4a5a8766c98b4476f6530d7d5cf/.yo-rc.json
  owner: tuannt39-study
  repo: jhipster-v4
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/Sanjeev-Hegde/corda-backend/blob/dcebfad1846f9536acd617a747bd7cf930c9f861/api/.yo-rc.json
  owner: Sanjeev-Hegde
  repo: corda-backend
  valid_check: 0
  valid_type: unknown
- name: .yo-rc.json
  url: >-
    https://github.com/vilashProgrammr/589/blob/3ab9db6d5b6898ebd30ecb2c785368b42f869b59/.yo-rc.json
  owner: vilashProgrammr
  repo: '589'
  valid_check: 0
  valid_type: unknown
