- name: passport-google-oauth.json
  url: >-
    https://api.github.com/repositories/73249815/contents/dependents/passport-google-oauth.json?ref=d8f40fe4968d49a2e2c25e9ac3ef7389be95e14f
  owner: nice-registry
  repo: dependent-packages
  domain_process: 0
  html_process: 0
- name: bower.json
  url: >-
    https://api.github.com/repositories/132891321/contents/bower.json?ref=f0d603406da74a5d656c11c109ad5643d39949d4
  owner: karthik2883
  repo: practice
  domain_process: 0
  html_process: 0
- name: package.json
  url: >-
    https://api.github.com/repositories/125514278/contents/package.json?ref=4e6316dbdd47657512ed194af023bd53950a1c15
  owner: Eduard20
  repo: rest-hapi
  domain_process: 0
  html_process: 0
- name: 3361951918.json
  url: >-
    https://api.github.com/repositories/174902682/contents/static/d/3361951918.json?ref=b86606524ddf2e082bc39c715b5a942affc9191a
  owner: rodrigovive
  repo: rodrigovive.github.io
  domain_process: 0
  html_process: 0
- name: .yo-rc.json
  url: >-
    https://api.github.com/repositories/106872676/contents/jhipster-oauth-backend/.yo-rc.json?ref=9324f073752a07be13ceaadb2ab2bbf6391284ba
  owner: mraible
  repo: ionic-jhipster-example
  domain_process: 0
  html_process: 0
- name: .yo-rc.json
  url: >-
    https://api.github.com/repositories/124416394/contents/.yo-rc.json?ref=a0fc7d221a23a04a5da1b140c69b946906e4dfd4
  owner: findhamid
  repo: uaa
  domain_process: 0
  html_process: 0
- name: .yo-rc.json
  url: >-
    https://api.github.com/repositories/123893381/contents/.yo-rc.json?ref=b1786c0b2090293a473d2880f7d61e8d48355a74
  owner: DhannyRaymond007
  repo: jhipsterSampleApplication
  domain_process: 0
  html_process: 0
- name: .yo-rc.json
  url: >-
    https://api.github.com/repositories/125007738/contents/.yo-rc.json?ref=211a20feb23f2a854d8a6cd92fa1fd415bf8c127
  owner: eswarn24
  repo: court
  domain_process: 0
  html_process: 0
- name: .yo-rc.json
  url: >-
    https://api.github.com/repositories/128881306/contents/.yo-rc.json?ref=7415002a6f0eea9356c3909a926decfa7ef374ee
  owner: hackpros
  repo: dsinterface
  domain_process: 0
  html_process: 0
- name: .yo-rc.json
  url: >-
    https://api.github.com/repositories/133554813/contents/.yo-rc.json?ref=3968b82e40b8a98020ca9e26d8a1b0a0deeefe16
  owner: tvprasad
  repo: MonolithicApp
  domain_process: 0
  html_process: 0
- name: .yo-rc.json
  url: >-
    https://api.github.com/repositories/132663751/contents/.yo-rc.json?ref=304edb07b6d6d82267cb3ff9e262c2d88f9934f6
  owner: utiliteez
  repo: jhSampleAngular1
  domain_process: 0
  html_process: 0
- name: .yo-rc.json
  url: >-
    https://api.github.com/repositories/133240688/contents/.yo-rc.json?ref=00a0b93b82a7e9dd5b9870405ffa028324ceee21
  owner: rodrigogrohl
  repo: elmoreplus
  domain_process: 0
  html_process: 0
- name: .yo-rc.json
  url: >-
    https://api.github.com/repositories/136445014/contents/.yo-rc.json?ref=bf2149d551bac17264c6e7e0051151584d825ab9
  owner: nonomoho
  repo: jhipsterFirstApplication
  domain_process: 0
  html_process: 0
- name: .yo-rc.json
  url: >-
    https://api.github.com/repositories/135122888/contents/.yo-rc.json?ref=6a0e7a5444f021ae66aaf204853e8e1c606e7c2a
  owner: limasqbank
  repo: monolithicOne
  domain_process: 0
  html_process: 0
- name: .yo-rc.json
  url: >-
    https://api.github.com/repositories/137090584/contents/.yo-rc.json?ref=090273266b95067e9858499447747a0fe643d1a4
  owner: hgspch
  repo: jhio-raible-blog-back
  domain_process: 0
  html_process: 0
- name: .yo-rc.json
  url: >-
    https://api.github.com/repositories/142290471/contents/.yo-rc.json?ref=cd461fdf8eb8853beb802d56c2978790acb5bd85
  owner: jetakasabaqi
  repo: warehouseproject
  domain_process: 0
  html_process: 0
- name: 9bd955b91d79e5b5fa4520a46458d49f81255540.json
  url: >-
    https://api.github.com/repositories/8051083/contents/System/NewsTrainer/data/entertainment_arts/9bd955b91d79e5b5fa4520a46458d49f81255540.json?ref=a7bcc25f6ea54aa38ee6d1666284d4d55af70285
  owner: feupeu
  repo: NyhedsfilterP2
  domain_process: 0
  html_process: 0
- name: ba47b06529ab335d0ede0b42c7b83127d1a019ff.json
  url: >-
    https://api.github.com/repositories/8051083/contents/System/NewsTrainer/data/entertainment_arts/ba47b06529ab335d0ede0b42c7b83127d1a019ff.json?ref=a7bcc25f6ea54aa38ee6d1666284d4d55af70285
  owner: feupeu
  repo: NyhedsfilterP2
  domain_process: 0
  html_process: 0
- name: 18ef2d42c1c897491fe01cf326e0f83bedd7cf56.json
  url: >-
    https://api.github.com/repositories/8051083/contents/System/NewsTrainer/data/entertainment_arts/18ef2d42c1c897491fe01cf326e0f83bedd7cf56.json?ref=a7bcc25f6ea54aa38ee6d1666284d4d55af70285
  owner: feupeu
  repo: NyhedsfilterP2
  domain_process: 0
  html_process: 0
- name: social-profiles.json
  url: >-
    https://api.github.com/repositories/144624429/contents/schemas/api/social-profiles.json?ref=cb6044f25e57c592c817053c92086b5f640beb8e
  owner: xamgore
  repo: python-stepik
  domain_process: 0
  html_process: 0
- name: .yo-rc.json
  url: >-
    https://api.github.com/repositories/143316204/contents/.yo-rc.json?ref=0a8d32d283984b95328fe4e805656d5c9d65c37b
  owner: gzheyts
  repo: productsapp
  domain_process: 0
  html_process: 0
